name: 'pypacktrends'
version: '1.0.0'
profile: 'pypacktrends'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"

on-run-end:
  - "{% if target.name == 'prod' %} {{ dbt_artifacts.upload_results(results) }} {% endif %}"

models:
  pypacktrends:
    +labels:
      service: dbt
    marts:
      pypi:
        +labels:
          domain: pypi
    staging:
      bq_public_data_pypi:
        +labels:
          domain: pypi
  dbt_artifacts:
    +schema: artifacts
    +labels:
      domain: dataops
