[project]
name = "dbt"
version = "0.1.0"
description = "dbt project for pypacktrends"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-bigquery>=1.8.3",
    "dbt-core>=1.8.8",
]

[dependency-groups]
dev = [
    "sqlfluff-templater-dbt>=3.2.5",
    "sqlfluff>=3.2.5",
]
