repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: name-tests-test
        args:
          - --pytest-test-first
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args:
          - --allow-untyped-decorators
          - --ignore-missing-imports
          - --strict
        additional_dependencies:
          - pydantic~=2.0
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.2.5
    hooks:
      - id: sqlfluff-lint
        additional_dependencies : ['dbt-bigquery==1.8.3', 'sqlfluff-templater-dbt']
      - id: sqlfluff-fix
        additional_dependencies : ['dbt-bigquery==1.8.3', 'sqlfluff-templater-dbt']
