services:
  backend:
    image: '${BACKEND_DOCKER_IMAGE_URL-ghcr.io/tylerhillery/pypacktrends/backend}:${BACKEND_TAG-latest}'
    restart: always
    networks:
      - caddy
    volumes:
      - ./data/:/app/data/
    environment:
      ENVIRONMENT: prod
      SENTRY_DSN: ${SENTRY_DSN}
      SQLITE_DB_PATH: ${SQLITE_DB_PATH-/app/data/pypacktrends.db}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health-check/"]
      interval: 10s
      timeout: 5s
      retries: 5

  caddy:
    container_name: caddy
    image: caddy/caddy:2.8.4-alpine
    restart: always
    networks:
      - caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./dbt/target:/srv/www/dbtdocs
      - caddy_data:/data
      - caddy_config:/config
    environment:
      DOMAIN: ${DOMAIN-pypacktrends.com}
      BACKEND_CONTAINER_NAME: ${BACKEND_CONTAINER_NAME-pypacktrends-backend-1}
      BACKEND_CONTAINER_PORT: ${BACKEND_CONTAINER_PORT-8000}

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:r0
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - caddy

  alloy:
    container_name: alloy
    image: grafana/alloy:latest
    restart: always
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - grafana_data:/var/lib/alloy/data
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    networks:
      - caddy

networks:
  caddy:
    name: caddy

volumes:
  caddy_data:
    name: caddy-data
  caddy_config:
    name: caddy-config
  grafana_data:
    name: grafana-data
