services:
  caddy:
    restart: no
    environment:
      DOMAIN: localhost

  backend:
    restart: no
    image: '${DOCKER_IMAGE_BACKEND-ghcr.io/tylerhillery/pypacktrends/backend}:${TAG-dev}'
    ports:
      - 8000:8000
    build:
      context: ./backend
    environment:
      ENVIRONMENT: dev
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild
  datasette:
    restart: no
    ports:
      - 8001:8001
