[project]
name = "infra"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pip>=24.3.1",
    "pulumi-docker-build>=0.0.7",
    "pulumi-docker>=4.5.7",
    "pulumi>=3.137.0",
]
