name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pulumi-preview:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Install dependencies
        run: |
            export UV_PROJECT_ENVIRONMENT="${pythonLocation}"
            uv sync --frozen
      - name: Pulumi Preview CICD Stack
        uses: pulumi/actions@v6
        with:
          command: preview
          stack-name: prod
          work-dir: ./infra
          comment-on-pr: true
          comment-on-summary: true
          github-token: ${{ secrets.GH_TOKEN }}
          color: always
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
