name: dbt CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  dbt-cd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dbt
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - name: Install python dependencies
        run: |
            export UV_PROJECT_ENVIRONMENT="${pythonLocation}"
            uv sync --frozen
      - name: Authenticate with GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.DBT_SERVICE_ACCOUNT_EMAIL }}
      - name: Debug GCP Auth
        run: |
          echo "Checking GOOGLE_APPLICATION_CREDENTIALS..."
          cat $GOOGLE_APPLICATION_CREDENTIALS
      - name: Activate GCP Auth
        run: gcloud auth application-default login --brief
      - name: Install dbt dependencies
        run: dbt deps
      - name: dbt Build
        run: dbt build --target prod
      - name: dbt Generate Docs
        run: dbt docs generate --target prod
      - name: Connect Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:cicd
      - name: Sync dbt docs to VPS
        run: rsync -avz --delete target/ github@pypacktrends-prod:/srv/www/dbtdocs
