name: Pulumi Up Prod
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  pulumi-up:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - name: Install dependencies
        run: |
            export UV_PROJECT_ENVIRONMENT="${pythonLocation}"
            uv sync --frozen
      - name: Connect Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:cicd
      - name: Pulumi Up
        id: pulumi
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: prod
          work-dir: ./infra
          comment-on-summary: true
          color: always
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Debug Pulumi outputs
        run: |
          echo "Ref value: ${{ steps.pulumi.outputs['docker-build-image-backend:ref'] }}"
          echo "Old ref value: ${{ steps.pulumi.outputs['docker-build-image-backend:old-ref'] }}"

      - name: Create Sentry release
        if: steps.pulumi.outputs['docker-build-image-backend:ref'] != steps.pulumi.outputs['docker-build-image-backend:old-ref']
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
