#cloud-config
ssh_pwauth: false
groups:
  - docker
users:
- name: "{{ vps_username }}"
  groups: sudo, docker, admin
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  lock_passwd: true

runcmd:
  # ssh configs
  - sed -i '/PermitRootLogin/d' /etc/ssh/sshd_config
  - echo "PermitRootLogin without-password" >> /etc/ssh/sshd_config
  - sed -i '/^AcceptEnv /d' /etc/ssh/sshd_config
  - echo "AcceptEnv LANG LC_* SENTRY_DSN" >> /etc/ssh/sshd_config
  - systemctl restart sshd

  # disable needrestart prompts
  - mkdir -p /etc/needrestart/conf.d
  - echo "\$nrconf{kernelhints} = -1;" > /etc/needrestart/conf.d/99disable-prompt.conf

  # system updates
  - apt update
  - DEBIAN_FRONTEND=noninteractive apt upgrade -y --allow-downgrades --allow-remove-essential --allow-change-held-packages
  - apt install -y sqlite3 unzip

  # docker configs
  - curl -fssl https://get.docker.com | sh

  # tailscale configs
  - curl -fsSL https://tailscale.com/install.sh | sh
  - sh -c "echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf && echo 'net.ipv6.conf.all.forwarding = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf && sudo sysctl -p /etc/sysctl.d/99-tailscale.conf"
  - tailscale up --ssh --accept-routes --authkey={{ tailscale_auth_key }}

  # install uv
  - curl -LsSf https://astral.sh/uv/install.sh -o /tmp/uv_install.sh # curl: (23) Failed writing body (1311 != 1378)
  - HOME="/root" UV_UNMANAGED_INSTALL="/usr/local/bin" sh /tmp/uv_install.sh # https://github.com/astral-sh/uv/issues/6965

  # make logs dir
  - sudo -u {{ vps_username }} mkdir /home/{{ vps_username }}/logs

  # clone the repository
  - sudo -u {{ vps_username }} git clone https://github.com/{{ github_username }}/{{ project_name }}.git {{ vps_project_path }}

  # create dbtdocs directory and set ownership
  - mkdir -p {{ vps_project_path }}/dbt/target
  - chown {{ vps_username }}:{{ vps_username }} {{ vps_project_path }}/dbt/target

  # create data directory and set ownership
  - mkdir -p {{ vps_project_path }}/data
  - chown {{ vps_username }}:{{ vps_username }} {{ vps_project_path }}/data

  # restore database
  - |
    sudo -u {{ vps_username }} \
      docker run --rm \
      -v {{ vps_project_path }}/data:/data \
      -v {{ vps_project_path }}/litestream/litestream.yml:/etc/litestream.yml \
      -e CLOUDFLARE_ACCOUNT_ID={{ cloudflare_account_id }} \
      -e CLOUDFLARE_R2_BUCKET_NAME={{ cloudflare_r2_bucket_name }} \
      -e CLOUDFLARE_R2_ACCESS_KEY_ID={{ cloudflare_r2_access_key_id }} \
      -e CLOUDFLARE_R2_SECRET_ACCESS_KEY={{ cloudflare_r2_secret_access_key }} \
      litestream/litestream restore -if-replica-exists \
      -o {{ vps_project_path }}/data/pypacktrends.db /data/pypacktrends.db

  # start containers using full path to docker-compose.yml
  - |
    sudo -u {{ vps_username }} \
      CLOUDFLARE_ACCOUNT_ID={{ cloudflare_account_id }} \
      CLOUDFLARE_R2_BUCKET_NAME={{ cloudflare_r2_bucket_name }} \
      CLOUDFLARE_R2_ACCESS_KEY_ID={{ cloudflare_r2_access_key_id }} \
      CLOUDFLARE_R2_SECRET_ACCESS_KEY={{ cloudflare_r2_secret_access_key }} \
      GRAFANA_API_KEY={{ grafana_api_key }} \
      GRAFANA_PROM_USER={{ grafana_prom_user }} \
      GRAFANA_LOKI_USER={{ grafana_loki_user }} \
      SENTRY_DSN={{ sentry_dsn }} \
      docker compose -f {{ vps_project_path }}/docker-compose.yml up -d

  # ufw configs
  - ufw allow OpenSSH
  - ufw default deny incoming
  - ufw enable
